eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  profiles:
    active: local
  config:
    import: "optional:configserver:http://127.0.0.1:8888"
  application:
    name: api-gateway-service
  cloud:
    config:
      name: api-gateway-service
      profile: local
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true

        - id: like-service
          uri: lb://LIKE-SERVICE
          predicates:
            - Path=/like-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true

        - id: posting-service
          uri: lb://POSTING-SERVICE
          predicates:
            - Path=/posting-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true

        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true

        - id: letter-service
          uri: lb://LETTER-SERVICE
          predicates:
            - Path=/letter-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true

        - id: follow-service
          uri: lb://FOLLOW-SERVICE
          predicates:
            - Path=/follow-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true

        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/report-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true

server:
  port: 8000

jwt:
  secret-key: secret-key-one-two-will-be-change-next-time

---

spring:
  config:
    activate:
      on-profile: dev
    import: configserver:http://127.0.0.1:8888
  cloud:
    config:
      name: api-gateway
      profile: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh
